name: Tag new version and build docker image

on:
  push:
    branches:
      - master

jobs:
  tag:
    name: Tag new version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true

  build-docker:
    name: Build and public docker image
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@0.1.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Remove "v" from tag
        id: replace-tag
        uses: frabert/replace-string-action@v1.1
        with:
          pattern: 'v(.+)'
          string: ${{ steps.latest-tag.outputs.tag}}
          replace-with: '$1'
      - name: Buid and publish docker image
        uses: matootie/github-docker@v1.0.1
        with:
          username: ericdallo
          personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
          imageTag: "${{ steps.replace-tag.outputs.tag }}"
