name: Tag and build docker image

on:
  push:
    branches:
      - master

jobs:
  tag:
    name: Tag new version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      id: tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
  
  build-docker:
    name: Build docker image and publish to Github Packages
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Echo tag
        run: echo ${{ steps.tag.outputs.new_tag }}
#       - name: Build and publish image
#         uses: matootie/github-docker@v1.0.1
#         with:
#           username: ericdallo
#           personalAccessToken: ${{ secrets.GITHUB_TOKEN }}
#           imageTag: ${{ format }}
